version: '3'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=holmescode.com --logLevel=DEBUG
    networks:
      - services
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/server/core/traefik.toml:/traefik.toml
      - /var/ssl:/var/ssl
    labels:
      - traefik.enable=false

networks:
  services:
    driver: overlay
