version: '3'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.domain=holmescode.com --logLevel=DEBUG
    networks:
      - public
      - private
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/server/core/traefik.toml:/traefik.toml
      - /var/ssl:/var/ssl
    deploy:
      labels:
        - traefik.enable=false

networks:
  public:
    driver: overlay
  private:
    driver: overlay
