defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/var/ssl/holmescode.com.crt"
      keyFile = "/var/ssl/holmescode.com.key"
      [[entryPoints.https.tls.certificates]]
      certFile = "/var/ssl/viper.cloud.crt"
      keyFile = "/var/ssl/viper.cloud.key"
