version: '3'

services:
  web:
    image: mattholmes/website:latest
    labels:
      - traefik.backend=holmescode-web
      - traefik.frontend.rule=Host:www.holmescode.com,holmescode.com
      - traefik.backend.loadbalancer.sticky=true
    networks:
      - services 
  
networks:
  services:
    external:
      name: core_services
