version: '3'

services:
  web:
    image: mattholmes/website:latest
    labels:
      - traefik.backend=holmescode-web
      - traefik.frontend.rule=Host:www.holmescode.com,holmescode.com
    networks:
      - internal
  
networks:
  internal:
    external:
      name: core_private
