version: '3'

services:
  web:
    image: mattholmes/website:latest
    deploy:
      labels:
        - traefik.port=5000
        - traefik.backend=holmescode-web
        - traefik.frontend.rule=Host:www.holmescode.com,holmescode.com
        - traefik.docker.network=core_services
        - traefik.backend.loadbalancer.sticky=true
    expose:
      - 5000
    networks:
      - services 
  
networks:
  services:
    external:
      name: core_services
